name: 'Click 315 Bot'

on:
  workflow_dispatch:
  #push:
    #branches: 
      #- master
  schedule:
    - cron: '30 2,8,14,20, * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Set up Python 3.9'
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: 'sleep'
      run: |
        python sleep.py
    - name: 'run Click 315'
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
        PUSH: ${{ secrets.PUSH }}
        RANGE: ${{ secrets.RANGE }}
        USERID: ${{ secrets.USERID }}
      run: |
        python main.py
        
